apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-redis
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-redis
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: redis