apiVersion: batch/v1
kind: Job
metadata:
  name: alpine-job
spec:
  completions: 1
  template:
    metadata:
      name: alpine-sleep
    spec:
      restartPolicy: Never
      containers:
        - image: alpine
          name: alpine-sleep
          command:
            - 'sh'
            - '-c'
            - 'sleep 60'
