apiVersion: v1 # версия API-чарта
appVersion: "1.0.0" # версия приложения внутри чарта
description: A Helm chart for Kubernetes  # описание приложения в одном предложении
name: my-chart # имя чарта (например, nginx)
version: 0.0.1 # версия чарта (должна быть по SemVer)