apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
              - name: http
                containerPort: {{ .Values.service.port }}
                protocol: TCP
          command:
            - ./podinfo
            {{- range .Values.arguments }}
            - {{ . }}
            {{- end }}
            {{- if .Values.redis.enabled }}
            - --cache-server=tcp://{{ .Values.redis.host }}:{{ .Values.redis.port }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}